version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "550432870296"
    IMAGE_REPO_NAME: "um-ecr"  # Name of your ECR repository
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Pre-build phase starting...
      - echo Logging in to ECR...
      - aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION --registry-ids $AWS_ACCOUNT_ID | docker login -u AWS --password-stdin https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build phase starting...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .  # Make sure your Dockerfile is in the root!
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

  post_build:
    commands:
      - echo Post-build phase starting...