apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::550432870296:role/codebuild-yoda-insurance-ms-code-build-service-role
      username: build
      groups:
        - system:masters